# Generated by Django 6.0.4 on 2026-04-23 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('plan_type', models.CharField(choices=[('basic', 'Базовый'), ('standard', 'Стандартный'), ('premium', 'Премиум')], max_length=20, verbose_name='Тип')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Длительность (дней)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (руб.)')),
                ('visits_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Лимит посещений (null = безлимит)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('visits_used', models.PositiveIntegerField(default=0, verbose_name='Посещений использовано')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('expired', 'Истёк'), ('frozen', 'Заморожен'), ('cancelled', 'Отменён')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='clients.client', verbose_name='Клиент')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan', verbose_name='Тарифный план')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма (руб.)')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('online', 'Онлайн')], max_length=20, verbose_name='Способ оплаты')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='subscriptions.subscription', verbose_name='Абонемент')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
